
; Example 3 - 44. Butterfly Unit of FCT ASM Listing for the TMS320C3x DSP

		RPTB	END_CENTER_LOOP
OUTSIDE_LOOP:							; TWO BUFFERFLIES ARE CALCULATED AT 
MIDSIDE_LOOP:							; 		THE SAME TIME

		LDF		*AR2, R2				; GET LOWER HALF OF EACH BUTTERFLY
||		LDF		*AR3, R3				; (THIS ALLOWS FOR MORE PARALLEL 
										; 		COMMANDS LATER)
		SUBF3	*AR3, *AR4, R1		; SUBSTRACT SECOND BUTTERFLY DATA
		SUBF3	*AR2, *AR1, R0		; SUBSTRACT FIRST BUTTERFLY DATA
		MPYF3	R1, *++AR7, R1		; MULTIPLY 2ND SUBSTRACTION RESULT 
||		ADDF3	R3, *AR4, R3			; BY COSINE COEEFICIENT; ADD SECOND
										; BUTTERFLY DATA
		MPYF3	R0, *--AR7, R0		; MULTIPLY 1ST SUBSTRACTION RESULT
||		ADDF3	R2, *AR1, R2			; BY COSINE COEEFICIENT; ADD FIRST
										; BUTTERFLY DATA
		STF		R1, *AR2++(IR1)%		; SAVE 2ND MULTIPLY RESULT IN LOWER
||		STF		R3, *AR4++(IR1)%		; HALF OF 2ND BUTTERFLY; SAVE 2ND 
										; ADDITION IN UPPER 2ND BUTTERFLY
END_CENTER_LOOP:
		STF		R0, *AR3++(IR1)%		; SAVE 1ST MULTIPLY RESULT IN LOWER
||		STF		R2, *AR1++(IR1)% 	; HALF OF 2ND BUTTERFLY; SAVE 1ST
										; ADDITION IN UPPER 1ST BUTTERFLY

